src/Entity/AnswerOption.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnswerOptionRepository")
 */
class AnswerOption
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $answer;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_right;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Question", inversedBy="answerOptions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $question;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnswer(): ?string
    {
        return $this->answer;
    }

    public function setAnswer(string $answer): self
    {
        $this->answer = $answer;

        return $this;
    }

    public function getIsRight(): ?bool
    {
        return $this->is_right;
    }

    public function setIsRight(bool $is_right): self
    {
        $this->is_right = $is_right;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }
}

src/Controller/PassExamController.php
<?php

namespace App\Controller;

use App\Entity\AnswerOption;
use App\Entity\Exam;
use App\Entity\Question;
use App\Entity\UserAnswer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class PassExamController extends AbstractController
{
  /**
   * @Route("/pass/exam/{exam}", name="passExam")
   * @param Exam $exam
   * @param Request $request
   * @return \Symfony\Component\HttpFoundation\Response
   */
  public function index(Exam $exam, Request $request)
  {
    $submittedToken = $request->request->get('token');

    if($this->isCsrfTokenValid('submit', $submittedToken)){

      $userAnswers = $request->request->all();
      array_pop($userAnswers); //удаляет последний элемент с токеном. Иначе ошибка
      $questionRepository = $this->getDoctrine()->getRepository(Question::class);
      $em = $this->getDoctrine()->getManager();
//      dump($result); die;

      foreach ($userAnswers as $questionId => $answer){
        //checkboxes return array where key is question id and value is array of answers
        if(is_array($answer)){
          foreach ($answer as $key => $sub_answer){
            $question = $questionRepository->find($questionId);
            $userAnswer = new UserAnswer();
            $userAnswer->setQuestion($question);
            $userAnswer->setAnswer($sub_answer);

            $em->persist($userAnswer);
            $em->flush();
          }

          continue;
        }

        $question = $questionRepository->find($questionId);
        $userAnswer = new UserAnswer();
        $userAnswer->setQuestion($question);
        $userAnswer->setAnswer($answer);

        $em->persist($userAnswer);
        $em->flush();
      }

      $examId = $exam->getId();
      return $this->redirect("/show/result/$examId");
    }

    return $this->render('passExam/index.html.twig', [
      'controller_name' => 'PassExamController',
      'exam' => $exam
    ]);
  }


  /**
   * @Route("/show/result/{exam}", name="showResult")
   * @param Exam $exam
   * @return \Symfony\Component\HttpFoundation\Response
   */
  public function showResult(Exam $exam)
  {
    $userAnswers = [];
    foreach ($exam->getQuestions() as $question){
      $questionId = $question->getId();

      foreach($question->getUserAnswer() as $userAnswer){

        //if question is a checkbox
        if($question->getType()->getId() == 2){
          $userAnswers["$questionId"][] = $userAnswer->getAnswer();

          continue;
        }

        $userAnswers["$questionId"] = $userAnswer->getAnswer();
      }
    }

    return $this->render('passExam/showResult.html.twig', [
      'exam' => $exam,
      'userAnswers' => $userAnswers
    ]);
  }
}

templates/passExam/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ exam.title }}{% endblock %}

{% block body %}
  <div class="container">
    <br><br>
    <h2 class="col-12">{{ exam.title }}</h2>
    <br>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <form action="{{ path('passExam', {'exam': exam.id}) }}" method="post">
            {% for question in exam.questions %}
              <br>
              <div class="content-element">
                <p class="h5 font-italic mb-3">{{ loop.index }}. {{ question.text }}</p>
                {% for  answer in question.answerOptions %}
                  {% if question.type.id == 1 %}
                    <label>
                      <input type="radio" name="{{ question.id }}" value="{{ answer.id }}">
                      <span>{{ answer.answer }}</span>
                    </label><br>
                  {% elseif question.type.id == 2 %}
                    <p class="mb-0">
                      <label>
                        <input type="checkbox" name="{{ question.id }}[]" value="{{ answer.id }}">
                        {{ answer.answer }}
                      </label>
                    </p>
                  {% else %}
                    <textarea name="{{ question.id }}" cols="30" rows="3"></textarea>
                  {% endif %}
                {% endfor %}
              </div>
            {% endfor %}
            <br>
            <input type="hidden" name="token" value="{{ csrf_token('submit') }}"/>
            <div class="row">
              <a href="" class="col-3">
                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Confirm</button>
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>

  </div>
{% endblock %}

templates/passExam/showResult.html.twig
{% extends 'base.html.twig' %}

{% block title %}Answers Page{% endblock %}

{% block body %}
  <div class="container">
    <br><br>
    <h2 class="col-12">Result: {{ exam.title }}</h2>
    <br>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          {% for question in exam.questions %}
            <br>
            <div class="content-element">
              <p class="h5 font-italic mb-3">{{ loop.index }}. {{ question.text }}</p>
              {% for  answer in question.answerOptions %}

                {#-------radiobuttons-------#}
                {% if question.type.id == 1 %}
                  <label>
                    <input type="radio">
                    <span
                      {% if answer.isRight and userAnswers[question.id] == answer.id %}
                        class="text-success font-weight-bold"
                      {% elseif answer.isRight == false and userAnswers[question.id] == answer.id %}
                        class="text-danger"
                      {% endif %}>
                        {{ answer.answer }}
                      </span>
                  </label><br>

                  {# -------checkboxes------- #}
                {% elseif question.type.id == 2 %}
                  <p class="mb-0">
                    <label
                      {% if answer.isRight and userAnswers[question.id][loop.index0] == answer.id %}
                        class="text-success font-weight-bold"
                      {% elseif answer.isRight == false and userAnswers[question.id][loop.index0] == answer.id %}
                      class="text-danger"
                        {% endif %}>
                      <input type="checkbox">&nbsp;{{ answer.answer }}
                    </label>
                  </p>

                  {# -------textarea------- #}
                {% elseif question.type.id == 3 %}
                  {% if userAnswers[question.id] == answer.answer %}
                    <span class="text-success font-weight-bold">{{ answer.answer }}</span>
                  {% else %}
                    <span class="text-danger">{{ userAnswers[question.id] }}</span><br>
                  {% endif %}
                {% endif %}

              {% endfor %}
            </div>
          {% endfor %}
        </div>
      </div>
    </div>

  </div>
{% endblock %}